# LM Studio Gemma 2B Coder Configuration
model_list:
  - model_name: gemma-2b-coder-lms
    litellm_params:
      model: openai/gemma-2b-coder
      api_base: http://127.0.0.1:1234/v1
      api_key: dummy-key

litellm_settings:
  success_callback: []
  failure_callback: []
  request_timeout: 300
  drop_params: false

general_settings:
  master_key: dummy-key
  completion_model: gemma-2b-coder-lms

# LM Studio Configuration
lmstudio_config:
  model_key: "gemma-2b-coder"
  server_port: 1234
  gpu_offload: "max"
  context_length: 32768

# Model info
model_info:
  name: "Gemma 2B Coder (LM Studio)"
  type: "local"
  provider: "LM Studio"
  context_length: 32768
  parameters: "2B"
  capabilities: ["coding", "tool_calling"]
  memory_requirement: "~1-2GB RAM"
  cost: "Free (local inference)"
  performance: "Fast inference with LM Studio optimization"
  notes: "Requires model to be downloaded in LM Studio first"