# LM Studio Qwen3 4B Thinking Configuration
# Model URL: https://lmstudio.ai/models/qwen/qwen3-4b-thinking-2507
model_list:
  - model_name: qwen3-4b-thinking-lms
    litellm_params:
      model: openai/qwen3-4b-thinking-2507
      api_base: http://127.0.0.1:1234/v1
      api_key: dummy-key

litellm_settings:
  success_callback: []
  failure_callback: []
  request_timeout: 300
  drop_params: false

general_settings:
  master_key: dummy-key
  completion_model: qwen3-4b-thinking-lms

# LM Studio Configuration
lmstudio_config:
  model_key: "qwen3-4b-thinking-2507"
  server_port: 1234
  gpu_offload: "max"
  context_length: 262144

# Model info
model_info:
  name: "Qwen3 4B Thinking (LM Studio)"
  type: "local"
  provider: "LM Studio"
  context_length: 262144
  parameters: "4B"
  capabilities: ["general", "coding", "reasoning", "tool_calling"]
  memory_requirement: "~2-4GB RAM"
  cost: "Free (local inference)"
  performance: "Efficient reasoning model with tool support"

# Alias configuration
alias_config:
  alias_name: "claude-lmstudio-qwen3-4b-thinking"
  runner_type: "local_lmstudio"
  description: "Qwen3 4B Thinking via LM Studio (~3GB, efficient reasoning)"