# LM Studio Qwen3 Next 80B Configuration
# Model URL: https://lmstudio.ai/models/qwen/qwen3-next-80b
model_list:
  - model_name: qwen3-next-80b-lms
    litellm_params:
      model: openai/qwen/qwen3-next-80b
      api_base: http://127.0.0.1:1234/v1
      api_key: dummy-key

litellm_settings:
  success_callback: []
  failure_callback: []
  request_timeout: 300
  drop_params: false

general_settings:
  master_key: dummy-key
  completion_model: qwen3-next-80b-lms

# LM Studio Configuration
lmstudio_config:
  model_key: "qwen/qwen3-next-80b"
  server_port: 1234
  gpu_offload: "max"
  context_length: 131072

# Model info
model_info:
  name: "Qwen3 Next 80B (LM Studio)"
  type: "local"
  provider: "LM Studio"
  context_length: 131072
  parameters: "80B total (3B active)"
  architecture: "Hybrid attention with high-sparsity MoE"
  capabilities: ["general", "coding", "reasoning", "tool_calling"]
  memory_requirement: "~8-12GB RAM (due to sparse MoE architecture)"
  cost: "Free (local inference)"
  performance: "80B model with only 3B active parameters - efficient inference"
  notes: "Mac MLX optimized, sparse MoE architecture makes it much more memory efficient than typical 80B models"

# Alias configuration
alias_config:
  alias_name: "claude-lmstudio-qwen3-next-80b"
  runner_type: "local_lmstudio"
  description: "Qwen3 Next 80B MoE via LM Studio (8-12GB, 3B active)"