# LM Studio Gemma 7B Instruct Configuration
model_list:
  - model_name: gemma-7b-instruct-lms
    litellm_params:
      model: openai/codegemma-1.1-7b-it
      api_base: http://127.0.0.1:1234/v1
      api_key: dummy-key

litellm_settings:
  success_callback: []
  failure_callback: []
  request_timeout: 300
  drop_params: false

general_settings:
  master_key: dummy-key
  completion_model: gemma-7b-instruct-lms

# LM Studio Configuration
lmstudio_config:
  model_key: "codegemma-1.1-7b-it"
  server_port: 1234
  gpu_offload: "max"
  context_length: 32768

# Model info
model_info:
  name: "Gemma 7B Instruct (LM Studio)"
  type: "local"
  provider: "LM Studio"
  context_length: 32768
  parameters: "7B"
  capabilities: ["general", "coding", "tool_calling"]
  memory_requirement: "~4-6GB RAM"
  cost: "Free (local inference)"
  performance: "Better than 2B, should handle tool calling"

# Alias configuration
alias_config:
  alias_name: "claude-lmstudio-gemma-7b"
  runner_type: "local_lmstudio"
  description: "CodeGemma 1.1 7B via LM Studio (5GB, better tools)"