# LM Studio SEED-OSS 36B Configuration
# Model URL: https://lmstudio.ai/models/bytedance/seed-oss-36b
model_list:
  - model_name: seed-oss-36b-lms
    litellm_params:
      model: openai/bytedance/seed-oss-36b
      api_base: http://127.0.0.1:1234/v1
      api_key: dummy-key

litellm_settings:
  success_callback: []
  failure_callback: []
  request_timeout: 300
  drop_params: false

general_settings:
  master_key: dummy-key
  completion_model: seed-oss-36b-lms

# LM Studio Configuration
lmstudio_config:
  model_key: "bytedance/seed-oss-36b"
  server_port: 1234
  gpu_offload: "max"
  context_length: 524288

# Model info
model_info:
  name: "SEED-OSS 36B (LM Studio)"
  type: "local"
  provider: "LM Studio"
  context_length: 524288
  parameters: "36B"
  capabilities: ["reasoning", "coding", "tool_usage", "long_context", "thinking_budget"]
  memory_requirement: "~21GB RAM"
  cost: "Free (local inference)"
  performance: "MATH: 81.7%, LiveCodeBench: 67.4%, RULER: 94.6%"
  notes: "Advanced reasoning model with flexible thinking budget control"

# Alias configuration
alias_config:
  alias_name: "claude-lmstudio-seed-36b"
  runner_type: "local_lmstudio"
  description: "SEED-OSS 36B (21GB, advanced reasoning)"
