# OpenRouter GLM-4.5-Air Free Configuration
model_list:
  - model_name: glm-4.5-air-paid
    litellm_params:
      model: openrouter/z-ai/glm-4.5-air
      api_base: https://openrouter.ai/api/v1
      api_key: ${OPENROUTER_API_KEY}

litellm_settings:
  success_callback: []
  failure_callback: []
  request_timeout: 120
  drop_params: true

general_settings:
  master_key: dummy-key
  completion_model: glm-4.5-air-paid
  
# Model info
model_info:
  name: "GLM-4.5-Air (OpenRouter)"
  type: "remote"
  provider: "OpenRouter"
  context_length: 131072
  capabilities: ["tool_calling", "reasoning", "coding"]
  cost: "~$0.5-2/1M tokens"