# Google Gemini Flash-Lite API Configuration (Free Tier Optimized)
model_list:
  - model_name: gemini-flash-lite
    litellm_params:
      model: gemini/gemini-2.5-flash-lite
      api_key: ${GEMINI_API_KEY}

litellm_settings:
  success_callback: []
  failure_callback: []
  request_timeout: 120
  drop_params: true

general_settings:
  master_key: dummy-key
  completion_model: gemini-flash-lite

# Model info
model_info:
  name: "Gemini 2.5 Flash-Lite"
  type: "remote"
  provider: "Google"
  context_length: 1048576
  capabilities: ["coding", "reasoning", "tool_calling"]
  cost: "Paid: requires billing setup, not free tier compatible"